CREATE TABLE tipos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    valor varchar(50) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    sprite VARCHAR(255) NOT NULL
);

CREATE TABLE pokemon (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero INT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    sprite VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500) NOT NULL DEFAULT ""
);

CREATE TABLE pokemon_tipos (
    pokemon INT,
    tipo INT,
    FOREIGN KEY (pokemon) REFERENCES pokemon(id) ON DELETE CASCADE,
    FOREIGN KEY (tipo) REFERENCES tipos(id) ON DELETE CASCADE
);

INSERT INTO tipos (valor, nombre, sprite) VALUES
    ("normal", "Normal", "./assets/img/tipos/1.png"),
    ("fighting", "Lucha", "./assets/img/tipos/2.png"),
    ("flying", "Volador", "./assets/img/tipos/3.png"),
    ("poison", "Veneno", "./assets/img/tipos/4.png"),
    ("ground", "Tierra", "./assets/img/tipos/5.png"),
    ("rock", "Roca", "./assets/img/tipos/6.png"),
    ("bug", "Bicho", "./assets/img/tipos/7.png"),
    ("ghost", "Fantasma", "./assets/img/tipos/8.png"),
    ("steel", "Acero", "./assets/img/tipos/9.png"),
    ("fire", "Fuego", "./assets/img/tipos/10.png"),
    ("water", "Agua", "./assets/img/tipos/11.png"),
    ("grass", "Planta", "./assets/img/tipos/12.png"),
    ("electric", "Eléctrico", "./assets/img/tipos/13.png"),
    ("psychic", "Psíquico", "./assets/img/tipos/14.png"),
    ("ice", "Hielo", "./assets/img/tipos/15.png"),
    ("dragon", "Dragón", "./assets/img/tipos/16.png"),
    ("dark", "Siniestro", "./assets/img/tipos/17.png"),
    ("unknown", "???", "./assets/img/tipos/10001.png");

INSERT INTO pokemon (numero, nombre, sprite, descripcion) VALUES
    (1, "Bulbasaur", "./assets/img/pokemon/1.png", "Una rara semilla le fue plantada en el lomo al nacer. La planta brota y crece con este Pokémon."),
    (2, "Ivysaur", "./assets/img/pokemon/2.png", "Este Pokémon tiene un bulbo en el lomo. Dicen que, al absorber nutrientes, el bulbo se transforma en una flor grande."),
    (3, "Venusaur", "./assets/img/pokemon/3.png", "Llena su cuerpo de energía con los rayos solares que captan los anchos pétalos de su flor."),
    (4, "Charmander", "./assets/img/pokemon/4.png", "La llama de su cola indica la fuerza vital de Charmander. Será brillante si está sano."),
    (5, "Charmeleon", "./assets/img/pokemon/5.png", "Suele usar la cola para derribar a su rival. Cuando lo tira, se vale de sus afiladas garras para acabar con él."),
    (6, "Charizard", "./assets/img/pokemon/6.png", "Cuando lanza una descarga de fuego supercaliente, la roja llama de su cola brilla más intensamente."),
    (7, "Squirtle", "./assets/img/pokemon/7.png", "Se protege con su caparazón y luego contraataca lanzando agua a presión cuando tiene oportunidad."),
    (8, "Wartortle", "./assets/img/pokemon/8.png", "Si es golpeado, esconderá su cabeza. Aun así, su cola puede seguir golpeando."),
    (9, "Blastoise", "./assets/img/pokemon/9.png", "Para acabar con su enemigo, lo aplasta con el peso de su cuerpo. En momentos de apuro, se esconde en el caparazón."),
    (10, "Caterpie", "./assets/img/pokemon/10.png", "Para protegerse despide un hedor horrible de sus antenas, con el que repele a sus enemigos."),
    (11, "Metapod", "./assets/img/pokemon/11.png", "Su frágil cuerpo está recubierto de una coraza dura como el acero. Permanece quieto en su desarrollo."),
    (12, "Butterfree", "./assets/img/pokemon/12.png", "Adora el néctar de las flores. Puede localizar hasta las más pequeñas cantidades de polen."),
    (13, "Weedle", "./assets/img/pokemon/13.png", "Suele habitar bosques y praderas. Tiene un afilado y venenoso aguijón de unos 5 cm encima de la cabeza."),
    (14, "Kakuna", "./assets/img/pokemon/14.png", "Casi incapaz de moverse, este Pokémon solo puede endurecer su caparazón para protegerse."),
    (15, "Beedrill", "./assets/img/pokemon/15.png", "Tiene 3 aguijones venenosos en sus patas y cola. Suelen pinchar a sus enemigos repetidas veces."),
    (16, "Pidgey", "./assets/img/pokemon/16.png", "Muy común en bosques y selvas. Aletea al nivel del suelo para levantar la gravilla."),
    (17, "Pidgeotto", "./assets/img/pokemon/17.png", "Tiene unas garras desarrolladas. Puede atrapar un Exeggcute y transportarlo desde una distancia de casi 100 km."),
    (18, "Pidgeot", "./assets/img/pokemon/18.png", "Cuando caza, vuela muy deprisa a ras del agua y sorprende a inocentes presas como Magikarp."),
    (19, "Rattata", "./assets/img/pokemon/19.png", "Vive allí donde haya comida disponible. Busca todo el día, sin descanso, algo comestible."),
    (20, "Raticate", "./assets/img/pokemon/20.png", "Lima sus colmillos royendo objetos duros. Con ellos puede destruir incluso paredes de hormigón."),
    (21, "Spearow", "./assets/img/pokemon/21.png", "Muy protector de su territorio, mueve sus cortas alas sin descanso para lanzarse a toda velocidad."),
    (22, "Fearow", "./assets/img/pokemon/22.png", "Con sus enormes y magníficas alas, puede seguir volando sin tener que aterrizar para descansar."),
    (23, "Ekans", "./assets/img/pokemon/23.png", "Cuanto más viejo, más crece este Pokémon. Por la noche, descansa en las ramas de los árboles."),
    (24, "Arbok", "./assets/img/pokemon/24.png", "El dibujo que tiene en la panza aterroriza. Los rivales más débiles salen huyendo al verlo."),
    (25, "Pikachu", "./assets/img/pokemon/25.png", "Levanta su cola para vigilar los alrededores. A veces, puede ser alcanzado por un rayo en esa pose."),
    (26, "Raichu", "./assets/img/pokemon/26.png", "Cuando se carga de electricidad, sus músculos se tensan y se vuelve más agresivo de lo normal."),
    (27, "Sandshrew", "./assets/img/pokemon/27.png", "Este Pokémon permanece bajo tierra. Si se siente amenazado, se enrosca para defenderse."),
    (28, "Sandslash", "./assets/img/pokemon/28.png", "Si cava a gran velocidad, puede que se le caigan las garras y púas. Vuelven a crecerle en un día."),
    (29, "Nidoran-F", "./assets/img/pokemon/29.png", "Aunque pequeñas, sus venenosas púas son muy peligrosas. Tienen un cuerno más pequeño que los machos."),
    (30, "Nidorina", "./assets/img/pokemon/30.png", "Tiene un carácter afable. Emite ondas ultrasónicas para confundir al enemigo."),
    (31, "Nidoqueen", "./assets/img/pokemon/31.png", "Usa su cuerpo duro y escamoso para sellar la entrada a su madriguera y protegerse de los depredadores."),
    (32, "Nidoran-M", "./assets/img/pokemon/32.png", "Saca las orejas por encima de la hierba para explorar el territorio. Le protege su cuerno venenoso."),
    (33, "Nidorino", "./assets/img/pokemon/33.png", "Levanta sus grandes orejas para vigilar. Si detecta algo, atacará de inmediato."),
    (34, "Nidoking", "./assets/img/pokemon/34.png", "Es fácil reconocerlo por tener una dura piel y un gran cuerno lleno de peligrosísimo veneno."),
    (35, "Clefairy", "./assets/img/pokemon/35.png", "Se dice que la felicidad llegará a quien vea a un grupo de Clefairy bailando a la luz de la luna llena."),
    (36, "Clefable", "./assets/img/pokemon/36.png", "Su oído es tan agudo que puede oír una aguja caer a 1 km. Vive en montañas solitarias."),
    (37, "Vulpix", "./assets/img/pokemon/37.png", "Cuando nace solo tiene una cola, pero a medida que crece, esta se va dividiendo desde la punta."),
    (38, "Ninetales", "./assets/img/pokemon/38.png", "Tiene nueve colas y un pelaje de color dorado. Dicen que este Pokémon llega a vivir 1000 años."),
    (39, "Jigglypuff", "./assets/img/pokemon/39.png", "Cautiva con la mirada a su enemigo y hace que se quede profundamente dormido mientras entona una dulce melodía."),
    (40, "Wigglytuff", "./assets/img/pokemon/40.png", "Su piel es tan suave que si dos de ellos se acurrucan juntos, no querrán separarse nunca."),
    (41, "Zubat", "./assets/img/pokemon/41.png", "Aunque carezca de ojos, puede detectar obstáculos con las ondas ultrasónicas que emite su boca."),
    (42, "Golbat", "./assets/img/pokemon/42.png", "Cuando ataque, seguirá chupando energía de su víctima, aunque pese tanto que ya no pueda volar."),
    (43, "Oddish", "./assets/img/pokemon/43.png", "Durante el día, se agazapa en el frío subsuelo huyendo del sol. La luz de la luna le hace crecer mucho."),
    (44, "Gloom", "./assets/img/pokemon/44.png", "¡Huele bastante mal! De todas formas, una de cada mil personas aprecian su fétido olor."),
    (45, "Vileplume", "./assets/img/pokemon/45.png", "Cuanto mayores son sus pétalos, más tóxico es su polen. Le pesa la cabeza y le cuesta mantenerla erguida."),
    (46, "Paras", "./assets/img/pokemon/46.png", "Lleva en el lomo dos setas parásitas llamadas tochukaso, que crecen con él."),
    (47, "Parasect", "./assets/img/pokemon/47.png", "Parasect está dominado por una seta parásita mayor que él. Dispersa esporas venenosas."),
    (48, "Venonat", "./assets/img/pokemon/48.png", "Sus grandes ojos son en realidad grupos de ojos diminutos. Por la noche se siente atraído por la luz."),
    (49, "Venomoth", "./assets/img/pokemon/49.png", "Lanza unas escamas que paralizan a cualquiera. Quien las toque, no podrá ni ponerse de pie."),
    (50, "Diglett", "./assets/img/pokemon/50.png", "Vive un metro por debajo del suelo, donde se alimenta de raíces. También aparece en la superficie."),
    (51, "Dugtrio", "./assets/img/pokemon/51.png", "En combate, cava la tierra, se esconde y sale de repente para golpear a su rival. Nunca se sabe por dónde puede aparecer."),
    (52, "Meowth", "./assets/img/pokemon/52.png", "Es de naturaleza nocturna. Le atraen los objetos brillantes."),
    (53, "Persian", "./assets/img/pokemon/53.png", "Aunque es muy admirado por el pelo, es difícil de entrenar como mascota, porque es un poco travieso."),
    (54, "Psyduck", "./assets/img/pokemon/54.png", "Padece continuamente dolores de cabeza. Cuando son muy fuertes, empieza a usar misteriosos poderes."),
    (55, "Golduck", "./assets/img/pokemon/55.png", "Aparece en ríos al anochecer. Puede usar poderes telequinéticos si su frente brilla misteriosamente."),
    (56, "Mankey", "./assets/img/pokemon/56.png", "Es peligroso acercarse si se enfada sin razón aparente, ya que no distingue entre amigos y enemigos."),
    (57, "Primeape", "./assets/img/pokemon/57.png", "Solo se calma cuando nadie está cerca. Llegar a ver ese momento es realmente difícil."),
    (58, "Growlithe", "./assets/img/pokemon/58.png", "Es muy agradable y leal. Para ahuyentar al enemigo, se pone a ladrar y a dar bocados."),
    (59, "Arcanine", "./assets/img/pokemon/59.png", "Un Pokémon muy admirado desde la antigüedad por su belleza. Corre ágilmente como si tuviera alas."),
    (60, "Poliwag", "./assets/img/pokemon/60.png", "Tiene una piel extraordinaria, fina y húmeda, que deja entrever las vísceras que tiene dispuestas en espiral."),
    (61, "Poliwhirl", "./assets/img/pokemon/61.png", "Capaz de vivir dentro o fuera del agua. Fuera del agua suda para mantener baboso su cuerpo."),
    (62, "Poliwrath", "./assets/img/pokemon/62.png", "Tiene músculos muy desarrollados. Es capaz de nadar en el océano sin descanso."),
    (63, "Abra", "./assets/img/pokemon/63.png", "Duerme 18 horas al día y mientras lo hace es capaz de usar una serie de poderes extrasensoriales."),
    (64, "Kadabra", "./assets/img/pokemon/64.png", "Cuando utiliza su poder psíquico, emite poderosas ondas alfa que pueden destruir dispositivos."),
    (65, "Alakazam", "./assets/img/pokemon/65.png", "Sus neuronas se multiplican continuamente durante su vida. Por eso, siempre lo recuerda todo."),
    (66, "Machop", "./assets/img/pokemon/66.png", "Levanta un Graveler para mantener sus músculos en forma. Domina todas las artes marciales."),
    (67, "Machoke", "./assets/img/pokemon/67.png", "Su musculoso cuerpo es tan fuerte que usa un cinto antifuerza para controlar sus movimientos."),
    (68, "Machamp", "./assets/img/pokemon/68.png", "Tiene cuatro brazos tan bien desarrollados que puede dar una serie de 1000 puñetazos en cuestión de dos segundos."),
    (69, "Bellsprout", "./assets/img/pokemon/69.png", "Aunque su cuerpo es extremadamente delgado, es muy rápido a la hora de capturar sus presas."),
    (70, "Weepinbell", "./assets/img/pokemon/70.png", "Las hojas que tiene actúan como cuchillas en combate. Otra de sus armas es el corrosivo fluido que expulsa."),
    (71, "Victreebel", "./assets/img/pokemon/71.png", "Dicen que vive en grandes colonias en el interior de las junglas, aunque nadie ha podido verificarlo."),
    (72, "Tentacool", "./assets/img/pokemon/72.png", "Su cuerpo se compone casi en exclusiva de agua. Lanza extraños rayos con sus ojos cristalinos."),
    (73, "Tentacruel", "./assets/img/pokemon/73.png", "Cuando caza, extiende los cortos tentáculos que tiene para atrapar e inmovilizar a su presa."),
    (74, "Geodude", "./assets/img/pokemon/74.png", "Aparecen en llanos y montañas. Como parecen rocas, la gente se tropieza con ellos o los pisa."),
    (75, "Graveler", "./assets/img/pokemon/75.png", "De naturaleza descuidada y libre, no le importa dañarse cuando baja rodando montañas."),
    (76, "Golem", "./assets/img/pokemon/76.png", "Se lanza montaña abajo y deja un surco desde la cima hasta el pie. Es mejor mantenerse alejado."),
    (77, "Ponyta", "./assets/img/pokemon/77.png", "Cuando nace, apenas puede tenerse en pie. Pero va fortaleciendo las patas en cuanto empieza a galopar."),
    (78, "Rapidash", "./assets/img/pokemon/78.png", "Muy competitivo, este Pokémon perseguirá a todo lo que se mueva rápido e intentará salir airoso."),
    (79, "Slowpoke", "./assets/img/pokemon/79.png", "Está siempre en su mundo, pero nadie sabe en qué piensa. Suele pescar con la cola."),
    (80, "Slowbro", "./assets/img/pokemon/80.png", "Tiene una cola tan apetecible, que el Shellder que va enganchado a ella no se soltará por nada del mundo."),
    (81, "Magnemite", "./assets/img/pokemon/81.png", "Las unidades a los lados de su cuerpo generan energía antigravitatoria para mantenerlo en el aire."),
    (82, "Magneton", "./assets/img/pokemon/82.png", "Lo constituye un grupo de Magnemite. Descarga potentes ondas magnéticas de alto voltaje."),
    (83, "Farfetchd", "./assets/img/pokemon/83.png", "El puerro que lleva es su mejor arma. Suele usarlo como espada para cortar cosas."),
    (84, "Doduo", "./assets/img/pokemon/84.png", "Este Pokémon de dos cabezas es el resultado de una mutación. Cuando corre, puede alcanzar casi 100 km por hora."),
    (85, "Dodrio", "./assets/img/pokemon/85.png", "Más vale no perder de vista ninguna de las tres cabezas. De lo contrario, el número de picotazos será enorme."),
    (86, "Seel", "./assets/img/pokemon/86.png", "Este Pokémon vive en icebergs. Nada en el mar y usa el cuerno de su cabeza para romper el hielo."),
    (87, "Dewgong", "./assets/img/pokemon/87.png", "Está recubierto de un luminoso pelaje blanco. Este Pokémon aumenta su actividad cuando bajan las temperaturas."),
    (88, "Grimer", "./assets/img/pokemon/88.png", "Nace de lodo alterado al filtrarse en el agua los rayos X reflejados por la Luna. Se alimenta de sustancias desagradables."),
    (89, "Muk", "./assets/img/pokemon/89.png", "Les encanta reunirse en zonas apestosas donde se acumula el lodo, haciendo su olor más insoportable."),
    (90, "Shellder", "./assets/img/pokemon/90.png", "La concha lo protege de cualquier tipo de ataque. Solo es vulnerable cuando se abre."),
    (91, "Cloyster", "./assets/img/pokemon/91.png", "A los Cloyster que viven en las fuertes corrientes marinas les crecen largas y afiladas púas en la concha."),
    (92, "Gastly", "./assets/img/pokemon/92.png", "Su etéreo cuerpo está hecho de gas. Puede envolver a un oponente de cualquier tamaño hasta ahogarlo."),
    (93, "Haunter", "./assets/img/pokemon/93.png", "Cuando tienes la sensación de que te están observando, seguro que es porque Haunter está cerca."),
    (94, "Gengar", "./assets/img/pokemon/94.png", "Se esconde entre las sombras. Se dice que donde Gengar acecha, la temperatura baja 5 °C."),
    (95, "Onix", "./assets/img/pokemon/95.png", "Cava a gran velocidad en busca de comida. Los túneles que deja son usados por los Diglett."),
    (96, "Drowzee", "./assets/img/pokemon/96.png", "Adormece a sus enemigos y se come sus sueños. A veces se pone enfermo si come pesadillas."),
    (97, "Hypno", "./assets/img/pokemon/97.png", "Lleva un péndulo en la mano. Una vez, hizo desaparecer a un niño al que había hipnotizado."),
    (98, "Krabby", "./assets/img/pokemon/98.png", "Ante el peligro, se camufla con las burbujas que desprende su boca, para parecer más grande."),
    (99, "Kingler", "./assets/img/pokemon/99.png", "La pinza tan grande que tiene posee una fuerza de 10 000 caballos de potencia. Pero, por su gran tamaño, cuesta moverla."),
    (100, "Voltorb", "./assets/img/pokemon/100.png", "Fue descubierto cuando se crearon las Poké Balls. Se dice que tiene algo que ver con ellas."),
    (101, "Electrode", "./assets/img/pokemon/101.png", "Explotan a la mínima. Por eso se les tiene mucho miedo. Estos Pokémon reciben el mote de Bomba Ball."),
    (102, "Exeggcute", "./assets/img/pokemon/102.png", "Estos seis huevos se comunican por telepatía. Si se separan, se pueden reunir rápidamente."),
    (103, "Exeggutor", "./assets/img/pokemon/103.png", "Sus tres cabezas piensan de forma independiente. Sin embargo, son amigas y no suelen discutir nunca."),
    (104, "Cubone", "./assets/img/pokemon/104.png", "Lleva puesto el cráneo de su madre. Cuando se siente solo se pone a gritar muy fuerte."),
    (105, "Marowak", "./assets/img/pokemon/105.png", "Es pequeño y siempre ha sido muy débil. Cuando empezó a usar huesos, se volvió más violento."),
    (106, "Hitmonlee", "./assets/img/pokemon/106.png", "Encoge y estira las patas a su antojo. Cuando las estira, es capaz de propinar una buena patada al enemigo."),
    (107, "Hitmonchan", "./assets/img/pokemon/107.png", "Los potentes golpes de sus brazos pueden pulverizar el hormigón. Descansa tras luchar tres minutos."),
    (108, "Lickitung", "./assets/img/pokemon/108.png", "Su larga lengua, recubierta de saliva pegajosa, se pega a todo, por lo que es muy útil."),
    (109, "Koffing", "./assets/img/pokemon/109.png", "Tiene forma de globo y es muy ligero. Está compuesto por gases tóxicos y apesta."),
    (110, "Weezing", "./assets/img/pokemon/110.png", "Si uno de los gemelos Koffing se infla, el otro se desinfla. Mezclan constantemente sus venenosos gases."),
    (111, "Rhyhorn", "./assets/img/pokemon/111.png", "Es muy fuerte, pero no especialmente listo. Es capaz de derribar rascacielos usando Placaje varias veces."),
    (112, "Rhydon", "./assets/img/pokemon/112.png", "La piel le sirve de escudo protector. Puede vivir en lava líquida a 2000 °C de temperatura."),
    (113, "Chansey", "./assets/img/pokemon/113.png", "Se dice que reparte felicidad. Se caracteriza por su compasión y reparte sus huevos entre la gente herida."),
    (114, "Tangela", "./assets/img/pokemon/114.png", "Se camufla con la multitud de lianas que envuelven su cuerpo y que no dejan de crecer a lo largo de toda su vida."),
    (115, "Kangaskhan", "./assets/img/pokemon/115.png", "Lleva a su cría en la bolsa de su panza. Solo deja que su cría salga a jugar cuando no siente peligro."),
    (116, "Horsea", "./assets/img/pokemon/116.png", "Es famoso por derribar a bichos voladores lanzando tinta desde la superficie del agua."),
    (117, "Seadra", "./assets/img/pokemon/117.png", "Las afiladas púas que le recubren el cuerpo se le erizan y pueden causar el debilitamiento con solo tocarlo."),
    (118, "Goldeen", "./assets/img/pokemon/118.png", "Nada a una velocidad de cinco nudos. Si siente peligro, golpea con su afilado cuerno."),
    (119, "Seaking", "./assets/img/pokemon/119.png", "En otoño, cuando se reproducen, se les puede ver nadando con energía por ríos y arroyos."),
    (120, "Staryu", "./assets/img/pokemon/120.png", "Aunque sus brazos se rompan podrán regenerarse, siempre y cuando su núcleo siga intacto."),
    (121, "Starmie", "./assets/img/pokemon/121.png", "Su núcleo central brilla con los colores del arcoíris. Para algunos tiene el valor de una gema."),
    (122, "Mr-Mime", "./assets/img/pokemon/122.png", "Para repeler ataques, solidifica el aire y crea muros invisibles con emanaciones de sus dedos."),
    (123, "Scyther", "./assets/img/pokemon/123.png", "Destroza a su presa con las guadañas que tiene. No es común que use las alas para volar."),
    (124, "Jynx", "./assets/img/pokemon/124.png", "Camina moviendo las caderas de forma llamativa. Puede hacer que la gente baile a su ritmo."),
    (125, "Electabuzz", "./assets/img/pokemon/125.png", "Por la superficie de su piel corre la electricidad. En la oscuridad, su cuerpo se torna blanquecino."),
    (126, "Magmar", "./assets/img/pokemon/126.png", "A este Pokémon se lo encontraron cerca de un volcán. Esta criatura ígnea tiene una temperatura corporal de unos 1200 °C."),
    (127, "Pinsir", "./assets/img/pokemon/127.png", "Atrapa presas con sus pinzas hasta que las parte en dos. Lanza lejos lo que no puede quebrar."),
    (128, "Tauros", "./assets/img/pokemon/128.png", "Después de animarse a luchar fustigándose con sus tres colas, carga a toda velocidad."),
    (129, "Magikarp", "./assets/img/pokemon/129.png", "No es precisamente rápido ni fuerte. Es el Pokémon más debilucho y simplón de todos los que hay."),
    (130, "Gyarados", "./assets/img/pokemon/130.png", "En la literatura antigua se dice que un Gyarados rebosante de violencia arrasó un poblado."),
    (131, "Lapras", "./assets/img/pokemon/131.png", "Son buenos de corazón. Muchos fueron capturados por ser tan pacíficos. Ahora hay muchos menos."),
    (132, "Ditto", "./assets/img/pokemon/132.png", "Puede alterar por completo su estructura celular para emular cualquier objeto que vea."),
    (133, "Eevee", "./assets/img/pokemon/133.png", "Un extraño Pokémon que se adapta a los entornos más hostiles gracias a sus diferentes evoluciones."),
    (134, "Vaporeon", "./assets/img/pokemon/134.png", "Prefiere las bellas costas. Con células parecidas al agua, podría fundirse en la misma."),
    (135, "Jolteon", "./assets/img/pokemon/135.png", "Todos los pelos de su cuerpo se ponen de punta si empieza a cargarse de electricidad."),
    (136, "Flareon", "./assets/img/pokemon/136.png", "Almacena llamas en su cuerpo, que alcanza una temperatura de 900 °C antes de un combate."),
    (137, "Porygon", "./assets/img/pokemon/137.png", "Pokémon creado por el hombre tras muchas investigaciones. Sus habilidades son básicas."),
    (138, "Omanyte", "./assets/img/pokemon/138.png", "Pokémon prehistórico que vivió en el océano primordial. Para nadar se valía de sus 10 tentáculos."),
    (139, "Omastar", "./assets/img/pokemon/139.png", "Tiene los tentáculos tan desarrollados que le sirven de manos y pies. Con ellos atrapa a su presa y le da un bocado."),
    (140, "Kabuto", "./assets/img/pokemon/140.png", "Se cree que habitó las playas hace 300 millones de años. Se protege con una dura concha."),
    (141, "Kabutops", "./assets/img/pokemon/141.png", "Repliega sus extremidades en el agua para hacerse más compacto, y mueve su concha para nadar rápido."),
    (142, "Aerodactyl", "./assets/img/pokemon/142.png", "Se regeneró a partir de material genético de un dinosaurio encontrado en ámbar. Cuando vuela emite escandalosos alaridos."),
    (143, "Snorlax", "./assets/img/pokemon/143.png", "No se encuentra satisfecho hasta que no se come 400 kg de comida cada día. Cuando acaba de comer, se queda dormido."),
    (144, "Articuno", "./assets/img/pokemon/144.png", "Legendario Pokémon pájaro capaz de generar ventiscas congelando la humedad del aire."),
    (145, "Zapdos", "./assets/img/pokemon/145.png", "Es un legendario pájaro Pokémon. Dicen que aparece entre las nubes lanzando enormes rayos brillantes."),
    (146, "Moltres", "./assets/img/pokemon/146.png", "Es más conocido como el legendario pájaro de fuego. Con cada aleteo crea brillantes llamas."),
    (147, "Dratini", "./assets/img/pokemon/147.png", "Se le llama el Pokémon Espejismo porque son muy pocos los que lo han visto. Se encontró su muda."),
    (148, "Dragonair", "./assets/img/pokemon/148.png", "Sus cristalinos orbes parecen darle al Pokémon el poder de controlar el clima libremente."),
    (149, "Dragonite", "./assets/img/pokemon/149.png", "A pesar del tamaño que tiene y de lo pesado que es, puede volar. Es capaz de dar la vuelta al mundo en solo 16 horas."),
    (150, "Mewtwo", "./assets/img/pokemon/150.png", "Fue creado por un científico tras años de horribles experimentos de ingeniería genética."),
    (151, "Mew", "./assets/img/pokemon/151.png", "Varios científicos lo consideran el antecesor de los Pokémon porque usa todo tipo de movimientos.");

INSERT INTO pokemon_tipos (pokemon, tipo) VALUES
    (1, 12),
    (1, 4),
    (2, 12),
    (2, 4),
    (3, 12),
    (3, 4),
    (4, 10),
    (5, 10),
    (6, 10),
    (6, 3),
    (7, 11),
    (8, 11),
    (9, 11),
    (10, 7),
    (11, 7),
    (12, 7),
    (12, 3),
    (13, 7),
    (13, 4),
    (14, 7),
    (14, 4),
    (15, 7),
    (15, 4),
    (16, 1),
    (16, 3),
    (17, 1),
    (17, 3),
    (18, 1),
    (18, 3),
    (19, 1),
    (20, 1),
    (21, 1),
    (21, 3),
    (22, 1),
    (22, 3),
    (23, 4),
    (24, 4),
    (25, 13),
    (26, 13),
    (27, 5),
    (28, 5),
    (29, 4),
    (30, 4),
    (31, 4),
    (31, 5),
    (32, 4),
    (33, 4),
    (34, 4),
    (34, 5),
    (35, 1),
    (36, 1),
    (37, 10),
    (38, 10),
    (39, 1),
    (40, 1),
    (41, 4),
    (41, 3),
    (42, 4),
    (42, 3),
    (43, 12),
    (43, 4),
    (44, 12),
    (44, 4),
    (45, 12),
    (45, 4),
    (46, 7),
    (46, 12),
    (47, 7),
    (47, 12),
    (48, 7),
    (48, 4),
    (49, 7),
    (49, 4),
    (50, 5),
    (51, 5),
    (52, 1),
    (53, 1),
    (54, 11),
    (55, 11),
    (56, 2),
    (57, 2),
    (58, 10),
    (59, 10),
    (60, 11),
    (61, 11),
    (62, 11),
    (62, 2),
    (63, 14),
    (64, 14),
    (65, 14),
    (66, 2),
    (67, 2),
    (68, 2),
    (69, 12),
    (69, 4),
    (70, 12),
    (70, 4),
    (71, 12),
    (71, 4),
    (72, 11),
    (72, 4),
    (73, 11),
    (73, 4),
    (74, 6),
    (74, 5),
    (75, 6),
    (75, 5),
    (76, 6),
    (76, 5),
    (77, 10),
    (78, 10),
    (79, 11),
    (79, 14),
    (80, 11),
    (80, 14),
    (81, 13),
    (81, 9),
    (82, 13),
    (82, 9),
    (83, 1),
    (83, 3),
    (84, 1),
    (84, 3),
    (85, 1),
    (85, 3),
    (86, 11),
    (87, 11),
    (87, 15),
    (88, 4),
    (89, 4),
    (90, 11),
    (91, 11),
    (91, 15),
    (92, 8),
    (92, 4),
    (93, 8),
    (93, 4),
    (94, 8),
    (94, 4),
    (95, 6),
    (95, 5),
    (96, 14),
    (97, 14),
    (98, 11),
    (99, 11),
    (100, 13),
    (101, 13),
    (102, 12),
    (102, 14),
    (103, 12),
    (103, 14),
    (104, 5),
    (105, 5),
    (106, 2),
    (107, 2),
    (108, 1),
    (109, 4),
    (110, 4),
    (111, 5),
    (111, 6),
    (112, 5),
    (112, 6),
    (113, 1),
    (114, 12),
    (115, 1),
    (116, 11),
    (117, 11),
    (118, 11),
    (119, 11),
    (120, 11),
    (121, 11),
    (121, 14),
    (122, 14),
    (123, 7),
    (123, 3),
    (124, 15),
    (124, 14),
    (125, 13),
    (126, 10),
    (127, 7),
    (128, 1),
    (129, 11),
    (130, 11),
    (130, 3),
    (131, 11),
    (131, 15),
    (132, 1),
    (133, 1),
    (134, 11),
    (135, 13),
    (136, 10),
    (137, 1),
    (138, 6),
    (138, 11),
    (139, 6),
    (139, 11),
    (140, 6),
    (140, 11),
    (141, 6),
    (141, 11),
    (142, 6),
    (142, 3),
    (143, 1),
    (144, 15),
    (144, 3),
    (145, 13),
    (145, 3),
    (146, 10),
    (146, 3),
    (147, 16),
    (148, 16),
    (149, 16),
    (149, 3),
    (150, 14),
    (151, 14);

